In [1]:
#читаем созданный в предыдущей программе набор данных
import pandas as pd
grades_df = pd.read_csv('grades_df.csv')
grades_df.head()

Unnamed: 0                time  \
0           0  28.03.2018 0:16:56   
1           1  28.03.2018 0:27:16   
2           2  28.03.2018 0:28:26   
3           3  28.03.2018 0:29:54   
4           4  28.03.2018 0:30:29   

                                       online_reason  algebra  geometry  \
0  Недостаточное качество или объем образовательн...      4.2       4.6   
1                             Не люблю рано вставать      3.7       3.2   
2        Хотел бы получить больше свободного времени      4.8       4.7   
3                             Не люблю рано вставать      4.8       4.9   
4                  Никогда не стал бы учиться онлайн      4.2       4.1   

   russian  literature  history  foreign  physics      ...       bio_other  \
0      4.0         4.7      4.7      4.9      4.9      ...               0   
1      4.7         4.8      4.5      4.9      3.3      ...               0   
2      4.6         4.3      3.6      4.7      4.7      ...               0   
3      4.9         5.0      4.8      4.9      4.7      ...               0   
4      4.7         4.7      4.7      4.9      4.3      ...               0   

   geo_other  for_other  it_other  soc_other his_other  no_other  vol_other  \
0          0          0         0          1         0         0          0   
1          0          0         1          0         0         0          1   
2          0          0         0          0         0         1          0   
3          0          0         0          0         0         0          0   
4          0          0         0          0         0         1          1   

   sport_other  events_other  
0            0             0  
1            0             1  
2            1             1  
3            1             1  
4            1             1  

[5 rows x 100 columns]

In [2]:
#задаем названия переменным
import numpy as np
adm_short = ['gum', 'it', 'econ', 'ped', 'med', 'est', 'ing']
subj_short = ['alg', 'geom', 'rus', 'lit', 'phy', 'chem', 'bio', 'geo', 'for', 'it', 'soc', 'his', 'no']
olymps_short = ['math', 'rus', 'lit', 'phy', 'chem', 'bio', 'geo', 'for', 'it', 'soc', 'his', 'no']
subjects_eng = 'algebra	geometry	russian	literature	history	foreign	physics	chemystry	geography	social	biology	informatics'.split('	')

olymps_full = np.concatenate([[a+'_town', a+'_region', a+'_state', a+'_other'] for a in olymps_short])
subj_base = [a+'_base' for a in subj_short]
subj_adv = [a+'_adv' for a in subj_short]
vol = ['vol_other', 'sport_other', 'events_other']

In [3]:
subj_base_log_predictions = []
subj_base_log_real = []
for i in subj_base:
    curr_subj_base = [subj for subj in subj_base if subj!=i]
    X_labeles = list(olymps_full)+list(curr_subj_base)+list(subj_adv)+list(subjects_eng)
    X_train, X_test, y_train, y_test = train_test_split(grades_df[X_labeles],
                                                        grades_df[i], random_state = 42, test_size = 0.5)
    log_reg = LogisticRegression()
    log_reg.fit(X_train, y_train)
    svc_reg = LinearSVC()
    svc_reg.fit(X_train, y_train)
    multy = MultinomialNB()
    multy.fit(X_train, y_train)
    ber = BernoulliNB()
    gauss = GaussianNB()
    gauss.fit(X_train, y_train)
    ber.fit(X_train, y_train)
    knn = KNeighborsClassifier(9)
    knn.fit(X_train, y_train)
    dummy = DummyClassifier('most_frequent')
    dummy.fit(X_train, y_train)
    print(i+'\nDummy score: {0}'.format(round(dummy.score(X_test, y_test),3)))
    print('Dummy AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in dummy.predict_proba(X_test)])))
    print('Logistic regression')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in log_reg.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(log_reg.score(X_train, y_train),3), round(log_reg.score(X_test, y_test),3)))
    print(confusion_matrix(log_reg.predict(X_test), y_test))
    print('LinearSVC')
    print('Train score: {0}\nTest score: {1}'.format(round(svc_reg.score(X_train, y_train),3), round(svc_reg.score(X_test, y_test),3)))
    print(confusion_matrix(svc_reg.predict(X_test), y_test))
    print('KNeighborsClassifier')
    print('Train score: {0}\nTest score: {1}'.format(round(knn.score(X_train, y_train),3), round(knn.score(X_test, y_test),3)))
    print(confusion_matrix(knn.predict(X_test), y_test))
    print('MultinomialNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in multy.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(multy.score(X_train, y_train),3), round(multy.score(X_test, y_test),3)))
    print(confusion_matrix(multy.predict(X_test), y_test))
    print('BernoulliNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in ber.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(ber.score(X_train, y_train),3), round(ber.score(X_test, y_test),3)))
    print(confusion_matrix(ber.predict(X_test), y_test))
    print('GaussianNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in gauss.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(gauss.score(X_train, y_train),3), 
                                                     round(gauss.score(X_test, y_test),3)))
    print(confusion_matrix(gauss.predict(X_test), y_test))
    print('\n')
    
    subj_base_log_predictions.append([a[1] for a in log_reg.predict_proba(X_test)])
    subj_base_log_real.append(list(y_test))

NameError: name 'train_test_split' is not defined

In [13]:
import random as rnd
predictions = [list(zip(predicts, subj_base)) for predicts in np.transpose(subj_base_log_predictions)]
reals = [list(zip(real, subj_base)) for real in np.transpose(subj_base_log_real)]
#print(sorted(real[111], reverse = True))
pred_dist = {}
real_dist = {}
for subj in subj_base:
    pred_dist[subj]=0
    real_dist[subj]=0
good = 0
num = len(reals)
top_num = 5
for i in range(num):
    pred = [preds[1] for preds in sorted(predictions[i], reverse = True)][0:top_num]
    #pred = rnd.sample(subj_base, top_num)
    real = [real[1] for real in sorted(reals[i], reverse = True) if real[0]==1]
    
    for z in real:
        if z in pred:
            good = good+1
            break
    for z in real:
        real_dist[z]+=1
    for z in pred:
        pred_dist[z]+=1
print(pred_dist)
print(real_dist) 
    
print('Top {0} score is {1}'.format(top_num, good/num))

{'alg_base': 11, 'geom_base': 17, 'rus_base': 18, 'lit_base': 53, 'phy_base': 56, 'chem_base': 52, 'bio_base': 50, 'geo_base': 92, 'for_base': 32, 'it_base': 85, 'soc_base': 65, 'his_base': 65, 'no_base': 39}
{'alg_base': 13, 'geom_base': 15, 'rus_base': 12, 'lit_base': 32, 'phy_base': 31, 'chem_base': 32, 'bio_base': 33, 'geo_base': 54, 'for_base': 16, 'it_base': 50, 'soc_base': 36, 'his_base': 39, 'no_base': 25}
Top 5 score is 0.9291338582677166


In [17]:
subj_adv_log_predictions = [] 
subj_adv_log_real = []

for i in subj_adv:
    curr_subj_adv = [subj for subj in subj_adv if subj!=i]
    X_labeles = list(olymps_full)+list(curr_subj_adv)+list(subj_base)+list(subjects_eng)
    X_train, X_test, y_train, y_test = train_test_split(grades_df[X_labeles],
                                                        grades_df[i], random_state = 42, test_size = 0.7)
    log_reg = LogisticRegression()
    log_reg.fit(X_train, y_train)
    svc_reg = LinearSVC()
    svc_reg.fit(X_train, y_train)
    multy = MultinomialNB()
    multy.fit(X_train, y_train)
    ber = BernoulliNB()
    gauss = GaussianNB()
    gauss.fit(X_train, y_train)
    ber.fit(X_train, y_train)
    knn = KNeighborsClassifier(9)
    knn.fit(X_train, y_train)
    dummy = DummyClassifier('most_frequent')
    dummy.fit(X_train, y_train)
    print(i+'\nDummy score: {0}'.format(round(dummy.score(X_test, y_test),3)))
    print('Dummy AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in dummy.predict_proba(X_test)])))
    print('Logistic regression')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in log_reg.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(log_reg.score(X_train, y_train),3), round(log_reg.score(X_test, y_test),3)))
    print(confusion_matrix(log_reg.predict(X_test), y_test))
    print('LinearSVC')
    print('Train score: {0}\nTest score: {1}'.format(round(svc_reg.score(X_train, y_train),3), round(svc_reg.score(X_test, y_test),3)))
    print(confusion_matrix(svc_reg.predict(X_test), y_test))
    print('KNeighborsClassifier')
    print('Train score: {0}\nTest score: {1}'.format(round(knn.score(X_train, y_train),3), round(knn.score(X_test, y_test),3)))
    print(confusion_matrix(knn.predict(X_test), y_test))
    print('MultinomialNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in multy.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(multy.score(X_train, y_train),3), round(multy.score(X_test, y_test),3)))
    print(confusion_matrix(multy.predict(X_test), y_test))
    print('BernoulliNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in ber.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(ber.score(X_train, y_train),3), round(ber.score(X_test, y_test),3)))
    print(confusion_matrix(ber.predict(X_test), y_test))
    print('GaussianNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in gauss.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(gauss.score(X_train, y_train),3), 
                                                     round(gauss.score(X_test, y_test),3)))
    print(confusion_matrix(gauss.predict(X_test), y_test))
    print('\n')
    subj_adv_log_predictions.append([a[1] for a in log_reg.predict_proba(X_test)])
    subj_adv_log_real.append(list(y_test))

alg_adv
Dummy score: 0.702
Dummy AUC score 0.5
Logistic regression
AUC score 0.7942641509433962
Train score: 0.96
Test score: 0.764
[[116  33]
 [  9  20]]
LinearSVC
Train score: 1.0
Test score: 0.747
[[108  28]
 [ 17  25]]
KNeighborsClassifier
Train score: 0.773
Test score: 0.708
[[125  52]
 [  0   1]]
MultinomialNB
AUC score 0.8469433962264151
Train score: 0.893
Test score: 0.747
[[117  37]
 [  8  16]]
BernoulliNB
AUC score 0.8561509433962264
Train score: 0.893
Test score: 0.742
[[114  35]
 [ 11  18]]
GaussianNB
AUC score 0.6376603773584906
Train score: 0.667
Test score: 0.567
[[58 10]
 [67 43]]


geom_adv
Dummy score: 0.815
Dummy AUC score 0.5
Logistic regression
AUC score 0.786833855799373
Train score: 0.973
Test score: 0.82
[[141  28]
 [  4   5]]
LinearSVC
Train score: 1.0
Test score: 0.831
[[137  22]
 [  8  11]]
KNeighborsClassifier
Train score: 0.84
Test score: 0.815
[[145  33]
 [  0   0]]
MultinomialNB
AUC score 0.8033437826541274
Train score: 0.893
Test score: 0.815
[[142  30]


In [31]:
predictions = [list(zip(predicts, subj_adv)) for predicts in np.transpose(subj_adv_log_predictions)]
reals = [list(zip(real, subj_adv)) for real in np.transpose(subj_adv_log_real)]
#print(sorted(real[111], reverse = True))
pred_dist = {}
real_dist = {}
for subj in subj_adv:
    pred_dist[subj]=0
    real_dist[subj]=0
good = 0
num = len(reals)
all_real = 0
top_num = 1
for i in range(num):
    pred = [preds[1] for preds in sorted(predictions[i], reverse = True)][0:top_num]
    #pred = rnd.sample(subj_base, top_num)
    real = [real[1] for real in sorted(reals[i], reverse = True) if real[0]==1]
    all_real += len(real)
    for z in real:
        if z in pred:
            good = good+1
            break
    for z in real:
        real_dist[z]+=1
    for z in pred:
        pred_dist[z]+=1
print(pred_dist)
print(real_dist) 
print('Top {0} score is {1}'.format(top_num, good/num))

{'alg_adv': 15, 'geom_adv': 3, 'rus_adv': 3, 'lit_adv': 8, 'phy_adv': 1, 'chem_adv': 0, 'bio_adv': 3, 'geo_adv': 0, 'for_adv': 65, 'it_adv': 25, 'soc_adv': 12, 'his_adv': 0, 'no_adv': 43}
{'alg_adv': 53, 'geom_adv': 33, 'rus_adv': 26, 'lit_adv': 36, 'phy_adv': 32, 'chem_adv': 20, 'bio_adv': 16, 'geo_adv': 12, 'for_adv': 83, 'it_adv': 39, 'soc_adv': 38, 'his_adv': 31, 'no_adv': 36}
Top 1 score is 0.5056179775280899


In [3]:
#загружаем необходимые для анализа данных пакеты из библиотеки sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import Lasso

#создаем массивы для хранения предсказаний по каждой модели
#и реальных значений переменных
subj_log_predictions = [] 
subj_log_real = []
subjs = subj_adv+subj_base
lasso_save = []

#цикл, который создает модель для каждого предмета
#базовый и продвинутый предмет считаются за два
for i in adm_short:
    #разбиение массива данных на тренировочную и тестовую части
    #тестовая часть составляет 40% от всего набора данных
    curr_subj = [subj for subj in subjs if subj!=i]
    X_labeles = list(olymps_full)+list(subjects_eng)+list(vol)
    X_train, X_test, y_train, y_test = train_test_split(grades_df[X_labeles],
                                                        grades_df[i], random_state = 42, test_size = 0.4)
    #создание моделей методами: логистической регрессии
    #SVM, тремя видами Naive Bayes, kNearestNeighbours -
    #и случайного классификатора
    log_reg = LogisticRegression()
    log_reg.fit(X_train, y_train)
    svc_reg = LinearSVC()
    svc_reg.fit(X_train, y_train)
    multy = MultinomialNB()
    multy.fit(X_train, y_train)
    ber = BernoulliNB()
    gauss = GaussianNB()
    gauss.fit(X_train, y_train)
    ber.fit(X_train, y_train)
    knn = KNeighborsClassifier(9)
    knn.fit(X_train, y_train)
    dummy = DummyClassifier('most_frequent')
    dummy.fit(X_train, y_train)
    #Вывод показателей по каждой модели
    print(i+'\nDummy score: {0}'.format(round(dummy.score(X_test, y_test),3)))
    print('Dummy AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in dummy.predict_proba(X_test)])))
    print('Logistic regression')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in log_reg.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(log_reg.score(X_train, y_train),3), round(log_reg.score(X_test, y_test),3)))
    print(confusion_matrix(log_reg.predict(X_test), y_test))
    print('LinearSVC')
    print('Train score: {0}\nTest score: {1}'.format(round(svc_reg.score(X_train, y_train),3), round(svc_reg.score(X_test, y_test),3)))
    print(confusion_matrix(svc_reg.predict(X_test), y_test))
    print('KNeighborsClassifier')
    print('Train score: {0}\nTest score: {1}'.format(round(knn.score(X_train, y_train),3), round(knn.score(X_test, y_test),3)))
    print(confusion_matrix(knn.predict(X_test), y_test))
    print('MultinomialNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in multy.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(multy.score(X_train, y_train),3), round(multy.score(X_test, y_test),3)))
    print(confusion_matrix(multy.predict(X_test), y_test))
    print('BernoulliNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in ber.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(ber.score(X_train, y_train),3), round(ber.score(X_test, y_test),3)))
    print(confusion_matrix(ber.predict(X_test), y_test))
    print('GaussianNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in gauss.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(gauss.score(X_train, y_train),3), 
                                                     round(gauss.score(X_test, y_test),3)))
    print(confusion_matrix(gauss.predict(X_test), y_test))
    print('Lasso')
    Lss = Lasso(0.01)
    Lss.fit(X_train, y_train)
    print(Lss.score(X_test, y_test))
    #Сохраняем данные по Лассо-модели для оценки
    #значимсти переменных
    lasso_save.append([x for x in zip(X_train.columns.values.tolist(), Lss.coef_)])
    print('\n')
    subj_log_predictions.append([a[1] for a in ber.predict_proba(X_test)])
    subj_log_real.append(list(y_test))

gum
Dummy score: 0.647
Dummy AUC score 0.5
Logistic regression
AUC score 0.6654040404040404
Train score: 0.881
Test score: 0.627
[[40 12]
 [26 24]]
LinearSVC
Train score: 0.901
Test score: 0.627
[[45 17]
 [21 19]]
KNeighborsClassifier
Train score: 0.762
Test score: 0.676
[[54 21]
 [12 15]]
MultinomialNB
AUC score 0.7028619528619529
Train score: 0.748
Test score: 0.696
[[52 17]
 [14 19]]
BernoulliNB
AUC score 0.6992845117845118
Train score: 0.755
Test score: 0.696
[[51 16]
 [15 20]]
GaussianNB
AUC score 0.5536616161616161
Train score: 0.536
Test score: 0.373
[[ 6  4]
 [60 32]]
Lasso
0.104259391469


it
Dummy score: 0.892
Dummy AUC score 0.5
Logistic regression
AUC score 0.6683316683316685
Train score: 0.894
Test score: 0.892
[[88  8]
 [ 3  3]]
LinearSVC
Train score: 0.974
Test score: 0.873
[[86  8]
 [ 5  3]]
KNeighborsClassifier
Train score: 0.861
Test score: 0.902
[[91 10]
 [ 0  1]]
MultinomialNB
AUC score 0.7052947052947053
Train score: 0.894
Test score: 0.892
[[89  9]
 [ 2  2]]
Berno

In [24]:
#цикл для оценки качества модели
probs = []
for e in range(1,6):
    predictions = [list(zip(predicts, subjs)) for predicts in np.transpose(subj_log_predictions)]
    reals = [list(zip(real, subjs)) for real in np.transpose(subj_log_real)]
    #print(sorted(real[111], reverse = True))
    pred_dist = {}
    real_dist = {}
    for subj in subjs:
        pred_dist[subj]=0
        real_dist[subj]=0
    good = 0
    num = len(reals)
    all_real = 0
    all_goods = 0
    top_num = e
    #цикл сравнивающий показатели для каждого пользователя в отдельности
    #с предсказанием, которое модель дала для пользователя
    for i in range(num):
        pred = [preds[1] for preds in sorted(predictions[i], reverse = True)][0:top_num]
        real = [real[1] for real in sorted(reals[i], reverse = True) if real[0]==1]
        for z in real:
            real_dist[z]+=1
        sum_real = sum([real_dist[x] for x in real_dist])
        #Два варианта создания случайных прогноза: с и без оглядки 
        #на распределение предметов по выборке
        #pred = np.random.choice(subjs, top_num, p = [real_dist[x]/sum_real for x in real_dist])
        #pred = np.random.choice(subjs, top_num)
        all_real += len(real)
        for z in real:
            if z in pred:
                good = good+1
                break
        for z in real:
            if z in pred:
                all_goods +=1
        for z in pred:
            pred_dist[z]+=1
    #Вывод статистики по получившейся модели
    print([(x, pred_dist[x]) for x in sorted(pred_dist, key=pred_dist.get, reverse = True)])
    print([(x, real_dist[x]) for x in sorted(real_dist, key=real_dist.get, reverse = True)])
    print('Top {0} score is {1}'.format(top_num, good/num))
    print('Mean real num is {0}'.format(all_real/num))
    print('Mean good num is {0}'.format(all_goods/num))
    probs.append(good/(num+1))

[('for_adv', 11), ('alg_adv', 8), ('geo_base', 7), ('his_base', 7), ('no_base', 7), ('no_adv', 6), ('geom_base', 6), ('it_base', 6), ('chem_base', 4), ('soc_adv', 3), ('his_adv', 3), ('geom_adv', 2), ('bio_base', 2), ('lit_adv', 1), ('it_adv', 1), ('phy_base', 1), ('soc_base', 1), ('rus_adv', 0), ('phy_adv', 0), ('chem_adv', 0), ('bio_adv', 0), ('geo_adv', 0), ('alg_base', 0), ('rus_base', 0), ('lit_base', 0), ('for_base', 0)]
[('for_adv', 37), ('geo_base', 32), ('it_base', 31), ('alg_adv', 22), ('soc_base', 22), ('his_base', 22), ('phy_base', 20), ('chem_base', 20), ('bio_base', 20), ('it_adv', 18), ('soc_adv', 17), ('no_adv', 17), ('lit_base', 17), ('geom_adv', 15), ('lit_adv', 15), ('phy_adv', 14), ('no_base', 14), ('rus_adv', 13), ('his_adv', 12), ('for_base', 10), ('chem_adv', 9), ('geo_adv', 8), ('geom_base', 8), ('rus_base', 8), ('alg_base', 7), ('bio_adv', 5)]
Top 1 score is 0.7368421052631579
Mean real num is 5.697368421052632
Mean good num is 0.7368421052631579
[('for_adv', 2

In [25]:
adm_log_predictions = []
adm_log_real = []
#загружаем необходимые для анализа данных пакеты из библиотеки sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

for i in adm_short:
    curr_subj = [subj for subj in subjs if subj!=i]
    X_labeles = list(olymps_full)+list(curr_subj)+list(subjects_eng)
    X_train, X_test, y_train, y_test = train_test_split(grades_df[X_labeles],
                                                        grades_df[i], random_state = 42, test_size = 0.3)
    log_reg = LogisticRegression(penalty='l1')
    log_reg.fit(X_train, y_train)
    svc_reg = LinearSVC()
    svc_reg.fit(X_train, y_train)
    multy = MultinomialNB()
    multy.fit(X_train, y_train)
    ber = BernoulliNB()
    gauss = GaussianNB()
    gauss.fit(X_train, y_train)
    ber.fit(X_train, y_train)
    knn = KNeighborsClassifier(9)
    knn.fit(X_train, y_train)
    dummy = DummyClassifier('most_frequent')
    dummy.fit(X_train, y_train)
    print(i+'\nDummy score: {0}'.format(round(dummy.score(X_test, y_test),3)))
    print('Dummy AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in dummy.predict_proba(X_test)])))
    print('Logistic regression')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in log_reg.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(log_reg.score(X_train, y_train),3), round(log_reg.score(X_test, y_test),3)))
    print(confusion_matrix(log_reg.predict(X_test), y_test))
    print('LinearSVC')
    print('Train score: {0}\nTest score: {1}'.format(round(svc_reg.score(X_train, y_train),3), round(svc_reg.score(X_test, y_test),3)))
    print(confusion_matrix(svc_reg.predict(X_test), y_test))
    print('KNeighborsClassifier')
    print('Train score: {0}\nTest score: {1}'.format(round(knn.score(X_train, y_train),3), round(knn.score(X_test, y_test),3)))
    print(confusion_matrix(knn.predict(X_test), y_test))
    print('MultinomialNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in multy.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(multy.score(X_train, y_train),3), round(multy.score(X_test, y_test),3)))
    print(confusion_matrix(multy.predict(X_test), y_test))
    print('BernoulliNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in ber.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(ber.score(X_train, y_train),3), round(ber.score(X_test, y_test),3)))
    print(confusion_matrix(ber.predict(X_test), y_test))
    print('GaussianNB')
    print('AUC score {0}'.format(roc_auc_score(y_test, [a[1] for a in gauss.predict_proba(X_test)])))
    print('Train score: {0}\nTest score: {1}'.format(round(gauss.score(X_train, y_train),3), 
                                                     round(gauss.score(X_test, y_test),3)))
    print(confusion_matrix(gauss.predict(X_test), y_test))
    print('\n')
    
    adm_log_predictions.append([a[1] for a in log_reg.predict_proba(X_test)])
    adm_log_real.append(list(y_test))

gum
Dummy score: 0.632
Dummy AUC score 0.5
Logistic regression
AUC score 0.6696428571428572
Train score: 0.887
Test score: 0.645
[[36 15]
 [12 13]]
LinearSVC
Train score: 0.96
Test score: 0.579
[[33 17]
 [15 11]]
KNeighborsClassifier
Train score: 0.791
Test score: 0.645
[[40 19]
 [ 8  9]]
MultinomialNB
AUC score 0.7247023809523809
Train score: 0.802
Test score: 0.684
[[35 11]
 [13 17]]
BernoulliNB
AUC score 0.7269345238095238
Train score: 0.819
Test score: 0.684
[[34 10]
 [14 18]]
GaussianNB
AUC score 0.6462053571428571
Train score: 0.52
Test score: 0.395
[[ 6  4]
 [42 24]]


it
Dummy score: 0.882
Dummy AUC score 0.5
Logistic regression
AUC score 0.7512437810945274
Train score: 0.938
Test score: 0.908
[[66  6]
 [ 1  3]]
LinearSVC
Train score: 1.0
Test score: 0.842
[[60  5]
 [ 7  4]]
KNeighborsClassifier
Train score: 0.87
Test score: 0.882
[[66  8]
 [ 1  1]]
MultinomialNB
AUC score 0.7296849087893864
Train score: 0.898
Test score: 0.868
[[64  7]
 [ 3  2]]
BernoulliNB
AUC score 0.7230514

In [26]:
#цикл для оценки качества модели
probs = []
for e in range(1,5):
    predictions = [list(zip(predicts, adm_short)) for predicts in np.transpose(adm_log_predictions)]
    reals = [list(zip(real, adm_short)) for real in np.transpose(adm_log_real)]
    #print(sorted(real[111], reverse = True))
    pred_dist = {}
    real_dist = {}
    for adm in adm_short:
        pred_dist[adm]=0
        real_dist[adm]=0
    good = 0
    num = len(reals)
    all_real = 0
    all_goods = 0
    top_num = e
    #цикл сравнивающий показатели для каждого пользователя в отдельности
    #с предсказанием, которое модель дала для пользователя
    for i in range(num):
        pred = [preds[1] for preds in sorted(predictions[i], reverse = True)][0:top_num]
        real = [real[1] for real in sorted(reals[i], reverse = True) if real[0]==1]
        for z in real:
            real_dist[z]+=1
        sum_real = sum([real_dist[x] for x in real_dist])
        #Два варианта создания случайных прогноза: с и без оглядки 
        #на распределение предметов по выборке
        #pred = np.random.choice(adm_short, top_num, p = [real_dist[x]/sum_real for x in real_dist])
        #pred = np.random.choice(subjs, top_num)
        all_real += len(real)
        for z in real:
            if z in pred:
                good = good+1
                break
        for z in real:
            if z in pred:
                all_goods +=1
        for z in pred:
            pred_dist[z]+=1
    #Вывод статистики по получившейся модели
    print([(x, pred_dist[x]) for x in sorted(pred_dist, key=pred_dist.get, reverse = True)])
    print([(x, real_dist[x]) for x in sorted(real_dist, key=real_dist.get, reverse = True)])
    print('Top {0} score is {1}'.format(top_num, good/(num+1)))
    print('Mean real num is {0}'.format(all_real/num))
    print('Mean good num is {0}'.format(all_goods/num))
    probs.append(good/(num+1))

[('gum', 36), ('econ', 15), ('ing', 15), ('it', 5), ('ped', 3), ('med', 2), ('est', 0)]
[('gum', 28), ('econ', 27), ('it', 9), ('ing', 9), ('ped', 6), ('med', 6), ('est', 4)]
Top 1 score is 0.42857142857142855
Mean real num is 1.1710526315789473
Mean good num is 0.4342105263157895
[('gum', 52), ('econ', 43), ('ing', 24), ('it', 11), ('med', 10), ('ped', 7), ('est', 5)]
[('gum', 28), ('econ', 27), ('it', 9), ('ing', 9), ('ped', 6), ('med', 6), ('est', 4)]
Top 2 score is 0.6623376623376623
Mean real num is 1.1710526315789473
Mean good num is 0.7368421052631579
[('gum', 61), ('econ', 53), ('ing', 37), ('it', 24), ('med', 24), ('ped', 17), ('est', 12)]
[('gum', 28), ('econ', 27), ('it', 9), ('ing', 9), ('ped', 6), ('med', 6), ('est', 4)]
Top 3 score is 0.7532467532467533
Mean real num is 1.1710526315789473
Mean good num is 0.868421052631579
[('gum', 64), ('econ', 62), ('ing', 52), ('it', 44), ('ped', 32), ('med', 30), ('est', 20)]
[('gum', 28), ('econ', 27), ('it', 9), ('ing', 9), ('ped', 

In [27]:
#метод для оценки доверительного интервала точности случайной модели
from scipy import stats
import scipy as sp
import math
 
n, min_max, mean, var, skew, kurt = stats.describe(probs)
std=math.sqrt(var)

R = stats.norm.interval(0.99,loc=mean,scale=std)
R 

(0.56450222229904634, 0.80134193354510952)

In [10]:
predictions = [list(zip(predicts, subjs)) for predicts in np.transpose(subj_log_predictions)]
reals = [list(zip(real, subjs)) for real in np.transpose(subj_log_real)]
#print(sorted(real[111], reverse = True))
pred_dist = {}
real_dist = {}
for subj in subjs:
    pred_dist[subj]=0
    real_dist[subj]=0
good = 0
num = len(reals)
all_real = 0
all_goods = 0
top_num = 4
for i in range(num):
    pred = [preds[1] for preds in sorted(predictions[i], reverse = True)][0:top_num]
    real = [real[1] for real in sorted(reals[i], reverse = True) if real[0]==1]
    for z in real:
        real_dist[z]+=1
    sum_real = sum([real_dist[x] for x in real_dist])
    #pred = np.random.choice(subjs, top_num, p = [real_dist[x]/sum_real for x in real_dist])
    #pred = np.random.choice(subjs, top_num)
    all_real += len(real)
    for z in real:
        if z in pred:
            good = good+1
            break
    for z in real:
        if z in pred:
            all_goods +=1
    for z in pred:
        pred_dist[z]+=1
print([(x, pred_dist[x]) for x in sorted(pred_dist, key=pred_dist.get, reverse = True)])
print([(x, real_dist[x]) for x in sorted(real_dist, key=real_dist.get, reverse = True)])
print('Top {0} score is {1}'.format(top_num, good/(num+1)))
print('Mean real num is {0}'.format(all_real/num))
print('Mean good num is {0}'.format(all_goods/num))

[('geo_base', 46), ('for_adv', 43), ('it_base', 34), ('his_base', 26), ('chem_base', 17), ('bio_base', 17), ('alg_adv', 16), ('soc_base', 15), ('lit_adv', 14), ('soc_adv', 14), ('lit_base', 13), ('no_adv', 9), ('it_adv', 7), ('phy_base', 7), ('for_base', 6), ('geom_adv', 4), ('phy_adv', 4), ('no_base', 4), ('his_adv', 3), ('alg_base', 2), ('geom_base', 2), ('rus_adv', 1), ('chem_adv', 0), ('bio_adv', 0), ('geo_adv', 0), ('rus_base', 0)]
[('for_adv', 37), ('geo_base', 32), ('it_base', 31), ('alg_adv', 22), ('soc_base', 22), ('his_base', 22), ('phy_base', 20), ('chem_base', 20), ('bio_base', 20), ('it_adv', 18), ('soc_adv', 17), ('no_adv', 17), ('lit_base', 17), ('geom_adv', 15), ('lit_adv', 15), ('phy_adv', 14), ('no_base', 14), ('rus_adv', 13), ('his_adv', 12), ('for_base', 10), ('chem_adv', 9), ('geo_adv', 8), ('geom_base', 8), ('rus_base', 8), ('alg_base', 7), ('bio_adv', 5)]
Top 4 score is 0.8571428571428571
Mean real num is 5.697368421052632
Mean good num is 1.5263157894736843


In [12]:
#создание и сохранение массива данных показателей модели Лассо
lasso_df = pd.DataFrame(columns = adm_short)
for lasso in range(len(lasso_save)):
    lasso_dict = {}
    for i in lasso_save[lasso]:
        lasso_dict[i[0]] = i[1]
    lasso_df = lasso_df.append(pd.Series(lasso_dict, name = subjs[lasso]))
lasso_df.to_csv('Lasso_params.csv', sep=';', na_rep='0', decimal =',')

In [17]:
lasso_df.to_csv('Lasso_params.csv', sep=';', na_rep='0', decimal =',')